package com.UrlShortener.Controller;
import com.UrlShortener.ApplicationProperties;
import com.UrlShortener.DTOs.PagedResult;
import com.UrlShortener.DTOs.ShortUrlDto;
import com.UrlShortener.Entities.User;
import com.UrlShortener.Services.ShortUrlService;
import com.UrlShortener.exceptions.ShortUrlNotFoundException;
import jakarta.validation.Valid;
import com.UrlShortener.DTOs.CreateShortUrlCmd;
import com.UrlShortener.DTOs.CreateShortUrlForm;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

import java.util.List;
import java.util.Optional;

@Controller
public class  HomeController {
    private final ShortUrlService shortUrlService;
    private final ApplicationProperties properties;
    private final SecurityUtils securityUtil;

    public HomeController(ShortUrlService shortUrlService, ApplicationProperties properties, SecurityUtils securityUtil) {
        this.shortUrlService = shortUrlService;
        this.properties = properties;
        this.securityUtil=securityUtil;
    }

    @GetMapping("/")
    public String home(
            @RequestParam(defaultValue = "1") Integer pageNo,
            Model model) {
        PagedResult<ShortUrlDto> shortUrls = shortUrlService.findPublicShortUrls(pageNo, properties.pageSize());
        model.addAttribute("shortUrls", shortUrls);
        model.addAttribute("baseUrl", properties.baseUrl());
        model.addAttribute("paginationUrl", "/");
        model.addAttribute("createShortUrlForm", new CreateShortUrlForm("", false, null));
        return "index";
    }

    @PostMapping("/short-urls")
    String createShortUrl(@ModelAttribute("createShortUrlForm") @Valid CreateShortUrlForm form,
                          /*
                          * ✅ @ModelAttribute :
                          *              Holds validation errors generated by @Valid
                          *              Must be placed immediately after the validated object
                          * 👉 If user submits:
                          *              1)Empty URL
                          *              2)Invalid format
                          *  Then bindingResult.hasErrors() becomes true.
                          * */
                          BindingResult bindingResult,

                          RedirectAttributes redirectAttributes,

                          /*
                          * ✅ Model :
                          * Used to send data from controller → view
                          * Attributes added here are accessible in HTML/JSP
                          * */
                          Model model) {
        if(bindingResult.hasErrors()) {
            PagedResult<ShortUrlDto> shortUrls = shortUrlService.findPublicShortUrls(1, properties.pageSize());
            model.addAttribute("shortUrls", shortUrls);
            model.addAttribute("baseUrl", properties.baseUrl());
            return "index";
        }

        try {
            Long userId = securityUtil.getCurrentUserId();
            CreateShortUrlCmd cmd = new CreateShortUrlCmd(
                    form.originalUrl(),
                    form.isPrivate(),
                    form.expirationInDays(),
                    userId
                    );
            var shortUrlDto = shortUrlService.createShortUrl(cmd);
            redirectAttributes.addFlashAttribute("successMessage", "Short URL created successfully ");
                    /* + properties.baseUrl()+"/s/"+shortUrlDto.shortKey());*/
        } catch (Exception e) {
            redirectAttributes.addFlashAttribute("errorMessage", "Failed to create short URL");
        }
        return "redirect:/";
    }

    @GetMapping("/s/{shortKey}")
    String redirectToOriginalUrl(@PathVariable String shortKey){
        Long userId = securityUtil.getCurrentUserId();
        Optional<ShortUrlDto> shortUrlDtoOptional = shortUrlService.accessShortUrl(shortKey, userId);
        if(shortUrlDtoOptional.isEmpty()){
            throw new ShortUrlNotFoundException("Invalid short key: "+shortKey);
        }

        ShortUrlDto shortUrlDto = shortUrlDtoOptional.get();
        return "redirect:"+shortUrlDto.originalUrl();
    }

    @GetMapping("/login")
    String loginForm(){
        return "login";
    }

    @GetMapping("/my-urls")
    public String showUserUrls(
            @RequestParam(defaultValue = "1") int pageNo,
            Model model) {
        var currentUserId = securityUtil.getCurrentUserId();
        PagedResult<ShortUrlDto> myUrls =
                shortUrlService.getUserShortUrls(currentUserId, pageNo, properties.pageSize());
        model.addAttribute("shortUrls", myUrls);
        model.addAttribute("baseUrl", properties.baseUrl());
        model.addAttribute("paginationUrl", "/my-urls");
        return "my-urls";
    }

    @PostMapping("/delete-urls")
    public String deleteUrls(
            @RequestParam(value = "ids", required = false) List<Long> ids,
            RedirectAttributes redirectAttributes) {
        if (ids == null || ids.isEmpty()) {
            redirectAttributes.addFlashAttribute(
                    "errorMessage", "No URLs selected for deletion");
            return "redirect:/my-urls";
        }
        try {
            var currentUserId = securityUtil.getCurrentUserId();
            shortUrlService.deleteUserShortUrls(ids, currentUserId);
            redirectAttributes.addFlashAttribute("successMessage",
                    "Selected URLs have been deleted successfully");
        } catch (Exception e) {
            redirectAttributes.addFlashAttribute("errorMessage",
                    "Error deleting URLs: " + e.getMessage());
        }
        return "redirect:/my-urls";
    }

}
